spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prueba
    username: postgres
    password: postgres
    platform: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  thymeleaf:
    cache: false
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type: TRACE
      springframework: ERROR