#spring:
#  messages:
#    basename: messages
#    always-use-message-format: false
#    cache-duration: 5s
#  couchbase:
#    bucket:
#      name: default
# Las siguientes propiedes tienen sus valores por defecto
# Por lo que no es necesario ponerlas
# a menos que se sobreescriban
spring:
  banner:
      location: classpath:banner.txt
  datasource:
    url: jdbc:mysql://localhost:3306/ninja2?useSSL=false
    username: root
    password: root
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    encoding: UTF-8
    mode: HTML
    servlet:
      content-type: text/html
    suffix: .html
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  error:
    whitelabel:
      enabled: false